- hosts: all
  become: yes
  gather_facts: false  # Opcional: puede ser true o false según tus necesidades
  tasks:
    - name: Crear usuario
      user:
        name: "{{ user }}"
        password: "{{ passw | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        comment: "{{ descrip }}"

    - name: Add sudo
      lineinfile:
        path: /etc/sudoers
        insertbefore: EOF
        line: "{{ user }}    ALL=(ALL:ALL) ALL"
        
    - name: Crear carpeta para llave
      file:
        path: /home/"{{ user }}"/.ssh
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Crear un directorio en el directorio de inicio del usuario
      file:
        path: /home/"{{ user }}"/.ssh/authorized_keys
        state: touch
        owner: "{{ user }}"
        group: "{{ user }}"
