---
  hosts: all
  become: yes  # Usar privilegios de superusuario (sudo)
  tasks:
    - name: Add_user
      user: "{{ user }}"
        name: "{{ name }}"
        password: "{{ passw }}"
        shell: /bin/bash  # (opcional) Especificar la shell por defecto
        state: present
