- hosts: all
  become: yes
  gather_facts: false  # Opcional: puede ser true o false según tus necesidades
  tasks:
    - name: Crear usuario
      user:
        name: "{{ user }}"
        password: "{{ passw | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        comment: "{{ descrip }}"

    - name: Add sudo
      lineinfile:
        path: /etc/sudoers
        insertbefore: EOF
        line: "{{ user }}    ALL=(ALL:ALL) ALL"
