- hosts: all
  gather_facts: false  # Opcional: puede ser true o false según tus necesidades
  tasks:
    - name: Crear usuario
      user:
        name: "{{ user }}"
        password: "{{ passw }}"
        shell: /bin/bash
        state: present
