- hosts: all
  become: true
  tasks:
    - name: Instalar iptables-persistent
      apt:
        name: iptables-persistent
        state: present
    
    - name: Crear reglas parala red de IT
      iptables:
        chain: INPUT
        protocol: tcp
        source:  "{{ IP }}"
        destination_port: 22
        jump: ACCEPT

    - name: Permitir tráfico relacionado/establecido
      iptables:
        chain: INPUT
        match: conntrack
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT

    - name: Permitir tráfico en interfaz de loopback
      iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT        

  
