- hosts: all
  become: true
  tasks:
    - name: Instalar iptables-persistent
      apt:
        name: iptables-persistent
        state: present
    
    - name: Crear reglas para la red de IT
      iptables:
        chain: INPUT
        protocol: tcp
        source:  "{{ IP }}"
        destination_port: "{{ ports }}"
        jump: ACCEPT
        when: "{{ type }}" == "dport"
        
    - name: Permitir tráfico desde una IP a múltiples puertos TCP usando multiport
      iptables:
        chain: INPUT
        protocol: tcp
        source: "{{ IP }}"
        multiport:
          dports: "{{ ports }}"
        jump: ACCEPT
         when: "{{ type }}" != "dport"
            
    - name: Permitir tráfico relacionado/establecido
      iptables:
        chain: INPUT
        match: conntrack
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT

    - name: Permitir tráfico en interfaz de loopback
      iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT        

  
