- hosts: all
  gather_facts: true
  vars:
    shell: 'ls'
  tasks:
    - name: Run the specified shell command
      shell: '{{ shell }}'
      register: result

    - name: Display the outcome
      debug:
        msg: '{{ result.stdout }}'
